package com.wll.sys.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_role
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysRole {
    /** */
    private String id;

    /** 角色名称*/
    private String name;

    /** 角色标识*/
    private String lable;

    /** */
    private String remarks;

    /** */
    private String str1;

    /** */
    private String str2;

    /** */
    private String str3;

    /** */
    private String str4;

    /** */
    private String str5;

    /** */
    private Date createDate;

    /** */
    private String createUserId;

    /** */
    private Date update;

    /** */
    private String updateUserId;

    /** */
    private String deleteTag;

    /** */
    private String deleteUserId;

    /** */
    private Integer num1;

    /** */
    private Integer num2;

    /** */
    private Integer num3;

    /** */
    private Integer num4;

    /** */
    private Integer num5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.id
     *
     * @return the value of sys_role.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.id
     *
     * @param id the value for sys_role.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.name
     *
     * @return the value of sys_role.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.name
     *
     * @param name the value for sys_role.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.lable
     *
     * @return the value of sys_role.lable
     *
     * @mbg.generated
     */
    public String getLable() {
        return lable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.lable
     *
     * @param lable the value for sys_role.lable
     *
     * @mbg.generated
     */
    public void setLable(String lable) {
        this.lable = lable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.remarks
     *
     * @return the value of sys_role.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.remarks
     *
     * @param remarks the value for sys_role.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.str_1
     *
     * @return the value of sys_role.str_1
     *
     * @mbg.generated
     */
    public String getStr1() {
        return str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.str_1
     *
     * @param str1 the value for sys_role.str_1
     *
     * @mbg.generated
     */
    public void setStr1(String str1) {
        this.str1 = str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.str_2
     *
     * @return the value of sys_role.str_2
     *
     * @mbg.generated
     */
    public String getStr2() {
        return str2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.str_2
     *
     * @param str2 the value for sys_role.str_2
     *
     * @mbg.generated
     */
    public void setStr2(String str2) {
        this.str2 = str2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.str_3
     *
     * @return the value of sys_role.str_3
     *
     * @mbg.generated
     */
    public String getStr3() {
        return str3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.str_3
     *
     * @param str3 the value for sys_role.str_3
     *
     * @mbg.generated
     */
    public void setStr3(String str3) {
        this.str3 = str3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.str_4
     *
     * @return the value of sys_role.str_4
     *
     * @mbg.generated
     */
    public String getStr4() {
        return str4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.str_4
     *
     * @param str4 the value for sys_role.str_4
     *
     * @mbg.generated
     */
    public void setStr4(String str4) {
        this.str4 = str4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.str_5
     *
     * @return the value of sys_role.str_5
     *
     * @mbg.generated
     */
    public String getStr5() {
        return str5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.str_5
     *
     * @param str5 the value for sys_role.str_5
     *
     * @mbg.generated
     */
    public void setStr5(String str5) {
        this.str5 = str5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.create_date
     *
     * @return the value of sys_role.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.create_date
     *
     * @param createDate the value for sys_role.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.create_user_id
     *
     * @return the value of sys_role.create_user_id
     *
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.create_user_id
     *
     * @param createUserId the value for sys_role.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.update
     *
     * @return the value of sys_role.update
     *
     * @mbg.generated
     */
    public Date getUpdate() {
        return update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.update
     *
     * @param update the value for sys_role.update
     *
     * @mbg.generated
     */
    public void setUpdate(Date update) {
        this.update = update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.update_user_id
     *
     * @return the value of sys_role.update_user_id
     *
     * @mbg.generated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.update_user_id
     *
     * @param updateUserId the value for sys_role.update_user_id
     *
     * @mbg.generated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.delete_tag
     *
     * @return the value of sys_role.delete_tag
     *
     * @mbg.generated
     */
    public String getDeleteTag() {
        return deleteTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.delete_tag
     *
     * @param deleteTag the value for sys_role.delete_tag
     *
     * @mbg.generated
     */
    public void setDeleteTag(String deleteTag) {
        this.deleteTag = deleteTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.delete_user_id
     *
     * @return the value of sys_role.delete_user_id
     *
     * @mbg.generated
     */
    public String getDeleteUserId() {
        return deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.delete_user_id
     *
     * @param deleteUserId the value for sys_role.delete_user_id
     *
     * @mbg.generated
     */
    public void setDeleteUserId(String deleteUserId) {
        this.deleteUserId = deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.num_1
     *
     * @return the value of sys_role.num_1
     *
     * @mbg.generated
     */
    public Integer getNum1() {
        return num1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.num_1
     *
     * @param num1 the value for sys_role.num_1
     *
     * @mbg.generated
     */
    public void setNum1(Integer num1) {
        this.num1 = num1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.num_2
     *
     * @return the value of sys_role.num_2
     *
     * @mbg.generated
     */
    public Integer getNum2() {
        return num2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.num_2
     *
     * @param num2 the value for sys_role.num_2
     *
     * @mbg.generated
     */
    public void setNum2(Integer num2) {
        this.num2 = num2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.num_3
     *
     * @return the value of sys_role.num_3
     *
     * @mbg.generated
     */
    public Integer getNum3() {
        return num3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.num_3
     *
     * @param num3 the value for sys_role.num_3
     *
     * @mbg.generated
     */
    public void setNum3(Integer num3) {
        this.num3 = num3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.num_4
     *
     * @return the value of sys_role.num_4
     *
     * @mbg.generated
     */
    public Integer getNum4() {
        return num4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.num_4
     *
     * @param num4 the value for sys_role.num_4
     *
     * @mbg.generated
     */
    public void setNum4(Integer num4) {
        this.num4 = num4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.num_5
     *
     * @return the value of sys_role.num_5
     *
     * @mbg.generated
     */
    public Integer getNum5() {
        return num5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.num_5
     *
     * @param num5 the value for sys_role.num_5
     *
     * @mbg.generated
     */
    public void setNum5(Integer num5) {
        this.num5 = num5;
    }
}