package com.wll.wll.entity;

import com.wll.wll.entity.baseentity.BaseEntity;
import com.wll.wll.entity.baseentity.DateEntity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pro_main
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ProMain extends BaseEntity<ProMain> {

    public ProMain(){
        super();
        setIsFather(false);
        setIsShow(true);
        setDeleteTag(false);
        setTag(true);
    }
    /** */
    private String userId;

    /** 序号*/
    private Integer sort;

    /** */
    private String d1;

    /** */
    private String d2;

    /** */
    private String d3;

    /** */
    private String d4;

    /** */
    private String d5;

    /** */
    private String d6;

    /** */
    private String d7;

    /** */
    private String d8;

    /** */
    private String d9;

    /** */
    private String d10;

    /** */
    private String d11;

    /** */
    private String d12;

    /** */
    private String d13;

    /** */
    private String d14;

    /** */
    private String d15;

    /** */
    private String d16;

    /** */
    private String d17;

    /** */
    private String d18;

    /** */
    private String d19;

    /** */
    private String d20;

    /** */
    private String d21;

    /** */
    private String d22;

    /** */
    private String d23;

    /** */
    private String d24;

    /** */
    private String d25;

    /** */
    private String d26;

    /** */
    private String d27;

    /** */
    private String d28;

    /** */
    private String d29;

    /** */
    private String d30;

    /** */
    private String d31;

    /** 创建时间*/
    private Date createDate;

    /** */
    private String createUserId;

    /** 更新时间*/
    private Date updateDate;

    /** */
    private String updateUserId;

    /** 是否删除（0 否 1是）*/
    private Boolean deleteTag;

    /** */
    private String deleteUserId;

    /** 系统 年*/
    private Integer year;

    /** 系统 月*/
    private Integer month;

    /** 系统 日*/
    private Integer day;

    /** 备注*/
    private String remarks;

    /** 应出勤天数*/
    private Integer ycqts;

    /** 实际出勤天数*/
    private Integer sjcqts;

    /** 事假*/
    private Integer sj;

    /** 病假*/
    private Integer bj;

    /** 年假*/
    private Integer nj;

    /** 婚假*/
    private Integer hj;

    /** 缺勤*/
    private Integer qq;

    /** 旷工*/
    private Integer kg;

    /** 忘打卡*/
    private Integer wdk;

    /** 迟到*/
    private Integer cd;

    /** 记录稳定状态 0 不稳定 1 稳定*/
    private Boolean tag;

    /** 列表显示 0 否 1 是*/
    private Boolean isShow;

    /** 是否有父 0 否 1是*/
    private Boolean isFather;

    /** 原始id*/
    private String pid;

    /** */
    private Integer num1;

    /** */
    private Integer num2;

    /** */
    private Integer num3;

    /** */
    private Integer num4;

    /** */
    private Integer num5;

    /** */
    private Integer num6;

    /** */
    private Integer num7;

    /** */
    private Integer num8;

    /** */
    private Integer num9;

    /** */
    private Integer num10;

    /** */
    private String str1;

    /** */
    private String str2;

    /** */
    private String str3;

    /** */
    private String str4;

    /** */
    private String str5;

    /** */
    private String str6;

    /** */
    private String str7;

    /** */
    private String str8;

    /** */
    private String str9;

    /** */
    private String str10;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.user_id
     *
     * @return the value of pro_main.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.user_id
     *
     * @param userId the value for pro_main.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.sort
     *
     * @return the value of pro_main.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.sort
     *
     * @param sort the value for pro_main.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d1
     *
     * @return the value of pro_main.d1
     *
     * @mbg.generated
     */
    public String getD1() {
        return d1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d1
     *
     * @param d1 the value for pro_main.d1
     *
     * @mbg.generated
     */
    public void setD1(String d1) {
        this.d1 = d1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d2
     *
     * @return the value of pro_main.d2
     *
     * @mbg.generated
     */
    public String getD2() {
        return d2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d2
     *
     * @param d2 the value for pro_main.d2
     *
     * @mbg.generated
     */
    public void setD2(String d2) {
        this.d2 = d2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d3
     *
     * @return the value of pro_main.d3
     *
     * @mbg.generated
     */
    public String getD3() {
        return d3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d3
     *
     * @param d3 the value for pro_main.d3
     *
     * @mbg.generated
     */
    public void setD3(String d3) {
        this.d3 = d3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d4
     *
     * @return the value of pro_main.d4
     *
     * @mbg.generated
     */
    public String getD4() {
        return d4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d4
     *
     * @param d4 the value for pro_main.d4
     *
     * @mbg.generated
     */
    public void setD4(String d4) {
        this.d4 = d4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d5
     *
     * @return the value of pro_main.d5
     *
     * @mbg.generated
     */
    public String getD5() {
        return d5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d5
     *
     * @param d5 the value for pro_main.d5
     *
     * @mbg.generated
     */
    public void setD5(String d5) {
        this.d5 = d5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d6
     *
     * @return the value of pro_main.d6
     *
     * @mbg.generated
     */
    public String getD6() {
        return d6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d6
     *
     * @param d6 the value for pro_main.d6
     *
     * @mbg.generated
     */
    public void setD6(String d6) {
        this.d6 = d6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d7
     *
     * @return the value of pro_main.d7
     *
     * @mbg.generated
     */
    public String getD7() {
        return d7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d7
     *
     * @param d7 the value for pro_main.d7
     *
     * @mbg.generated
     */
    public void setD7(String d7) {
        this.d7 = d7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d8
     *
     * @return the value of pro_main.d8
     *
     * @mbg.generated
     */
    public String getD8() {
        return d8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d8
     *
     * @param d8 the value for pro_main.d8
     *
     * @mbg.generated
     */
    public void setD8(String d8) {
        this.d8 = d8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d9
     *
     * @return the value of pro_main.d9
     *
     * @mbg.generated
     */
    public String getD9() {
        return d9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d9
     *
     * @param d9 the value for pro_main.d9
     *
     * @mbg.generated
     */
    public void setD9(String d9) {
        this.d9 = d9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d10
     *
     * @return the value of pro_main.d10
     *
     * @mbg.generated
     */
    public String getD10() {
        return d10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d10
     *
     * @param d10 the value for pro_main.d10
     *
     * @mbg.generated
     */
    public void setD10(String d10) {
        this.d10 = d10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d11
     *
     * @return the value of pro_main.d11
     *
     * @mbg.generated
     */
    public String getD11() {
        return d11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d11
     *
     * @param d11 the value for pro_main.d11
     *
     * @mbg.generated
     */
    public void setD11(String d11) {
        this.d11 = d11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d12
     *
     * @return the value of pro_main.d12
     *
     * @mbg.generated
     */
    public String getD12() {
        return d12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d12
     *
     * @param d12 the value for pro_main.d12
     *
     * @mbg.generated
     */
    public void setD12(String d12) {
        this.d12 = d12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d13
     *
     * @return the value of pro_main.d13
     *
     * @mbg.generated
     */
    public String getD13() {
        return d13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d13
     *
     * @param d13 the value for pro_main.d13
     *
     * @mbg.generated
     */
    public void setD13(String d13) {
        this.d13 = d13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d14
     *
     * @return the value of pro_main.d14
     *
     * @mbg.generated
     */
    public String getD14() {
        return d14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d14
     *
     * @param d14 the value for pro_main.d14
     *
     * @mbg.generated
     */
    public void setD14(String d14) {
        this.d14 = d14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d15
     *
     * @return the value of pro_main.d15
     *
     * @mbg.generated
     */
    public String getD15() {
        return d15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d15
     *
     * @param d15 the value for pro_main.d15
     *
     * @mbg.generated
     */
    public void setD15(String d15) {
        this.d15 = d15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d16
     *
     * @return the value of pro_main.d16
     *
     * @mbg.generated
     */
    public String getD16() {
        return d16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d16
     *
     * @param d16 the value for pro_main.d16
     *
     * @mbg.generated
     */
    public void setD16(String d16) {
        this.d16 = d16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d17
     *
     * @return the value of pro_main.d17
     *
     * @mbg.generated
     */
    public String getD17() {
        return d17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d17
     *
     * @param d17 the value for pro_main.d17
     *
     * @mbg.generated
     */
    public void setD17(String d17) {
        this.d17 = d17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d18
     *
     * @return the value of pro_main.d18
     *
     * @mbg.generated
     */
    public String getD18() {
        return d18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d18
     *
     * @param d18 the value for pro_main.d18
     *
     * @mbg.generated
     */
    public void setD18(String d18) {
        this.d18 = d18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d19
     *
     * @return the value of pro_main.d19
     *
     * @mbg.generated
     */
    public String getD19() {
        return d19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d19
     *
     * @param d19 the value for pro_main.d19
     *
     * @mbg.generated
     */
    public void setD19(String d19) {
        this.d19 = d19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d20
     *
     * @return the value of pro_main.d20
     *
     * @mbg.generated
     */
    public String getD20() {
        return d20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d20
     *
     * @param d20 the value for pro_main.d20
     *
     * @mbg.generated
     */
    public void setD20(String d20) {
        this.d20 = d20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d21
     *
     * @return the value of pro_main.d21
     *
     * @mbg.generated
     */
    public String getD21() {
        return d21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d21
     *
     * @param d21 the value for pro_main.d21
     *
     * @mbg.generated
     */
    public void setD21(String d21) {
        this.d21 = d21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d22
     *
     * @return the value of pro_main.d22
     *
     * @mbg.generated
     */
    public String getD22() {
        return d22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d22
     *
     * @param d22 the value for pro_main.d22
     *
     * @mbg.generated
     */
    public void setD22(String d22) {
        this.d22 = d22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d23
     *
     * @return the value of pro_main.d23
     *
     * @mbg.generated
     */
    public String getD23() {
        return d23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d23
     *
     * @param d23 the value for pro_main.d23
     *
     * @mbg.generated
     */
    public void setD23(String d23) {
        this.d23 = d23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d24
     *
     * @return the value of pro_main.d24
     *
     * @mbg.generated
     */
    public String getD24() {
        return d24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d24
     *
     * @param d24 the value for pro_main.d24
     *
     * @mbg.generated
     */
    public void setD24(String d24) {
        this.d24 = d24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d25
     *
     * @return the value of pro_main.d25
     *
     * @mbg.generated
     */
    public String getD25() {
        return d25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d25
     *
     * @param d25 the value for pro_main.d25
     *
     * @mbg.generated
     */
    public void setD25(String d25) {
        this.d25 = d25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d26
     *
     * @return the value of pro_main.d26
     *
     * @mbg.generated
     */
    public String getD26() {
        return d26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d26
     *
     * @param d26 the value for pro_main.d26
     *
     * @mbg.generated
     */
    public void setD26(String d26) {
        this.d26 = d26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d27
     *
     * @return the value of pro_main.d27
     *
     * @mbg.generated
     */
    public String getD27() {
        return d27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d27
     *
     * @param d27 the value for pro_main.d27
     *
     * @mbg.generated
     */
    public void setD27(String d27) {
        this.d27 = d27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d28
     *
     * @return the value of pro_main.d28
     *
     * @mbg.generated
     */
    public String getD28() {
        return d28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d28
     *
     * @param d28 the value for pro_main.d28
     *
     * @mbg.generated
     */
    public void setD28(String d28) {
        this.d28 = d28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d29
     *
     * @return the value of pro_main.d29
     *
     * @mbg.generated
     */
    public String getD29() {
        return d29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d29
     *
     * @param d29 the value for pro_main.d29
     *
     * @mbg.generated
     */
    public void setD29(String d29) {
        this.d29 = d29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d30
     *
     * @return the value of pro_main.d30
     *
     * @mbg.generated
     */
    public String getD30() {
        return d30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d30
     *
     * @param d30 the value for pro_main.d30
     *
     * @mbg.generated
     */
    public void setD30(String d30) {
        this.d30 = d30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.d31
     *
     * @return the value of pro_main.d31
     *
     * @mbg.generated
     */
    public String getD31() {
        return d31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.d31
     *
     * @param d31 the value for pro_main.d31
     *
     * @mbg.generated
     */
    public void setD31(String d31) {
        this.d31 = d31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.create_date
     *
     * @return the value of pro_main.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.create_date
     *
     * @param createDate the value for pro_main.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.create_user_id
     *
     * @return the value of pro_main.create_user_id
     *
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.create_user_id
     *
     * @param createUserId the value for pro_main.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.update_date
     *
     * @return the value of pro_main.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.update_date
     *
     * @param updateDate the value for pro_main.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.update_user_id
     *
     * @return the value of pro_main.update_user_id
     *
     * @mbg.generated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.update_user_id
     *
     * @param updateUserId the value for pro_main.update_user_id
     *
     * @mbg.generated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.delete_tag
     *
     * @return the value of pro_main.delete_tag
     *
     * @mbg.generated
     */
    public Boolean getDeleteTag() {
        return deleteTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.delete_tag
     *
     * @param deleteTag the value for pro_main.delete_tag
     *
     * @mbg.generated
     */
    public void setDeleteTag(Boolean deleteTag) {
        this.deleteTag = deleteTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.delete_user_id
     *
     * @return the value of pro_main.delete_user_id
     *
     * @mbg.generated
     */
    public String getDeleteUserId() {
        return deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.delete_user_id
     *
     * @param deleteUserId the value for pro_main.delete_user_id
     *
     * @mbg.generated
     */
    public void setDeleteUserId(String deleteUserId) {
        this.deleteUserId = deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.year
     *
     * @return the value of pro_main.year
     *
     * @mbg.generated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.year
     *
     * @param year the value for pro_main.year
     *
     * @mbg.generated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.month
     *
     * @return the value of pro_main.month
     *
     * @mbg.generated
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.month
     *
     * @param month the value for pro_main.month
     *
     * @mbg.generated
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.day
     *
     * @return the value of pro_main.day
     *
     * @mbg.generated
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.day
     *
     * @param day the value for pro_main.day
     *
     * @mbg.generated
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.remarks
     *
     * @return the value of pro_main.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.remarks
     *
     * @param remarks the value for pro_main.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.ycqts
     *
     * @return the value of pro_main.ycqts
     *
     * @mbg.generated
     */
    public Integer getYcqts() {
        return ycqts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.ycqts
     *
     * @param ycqts the value for pro_main.ycqts
     *
     * @mbg.generated
     */
    public void setYcqts(Integer ycqts) {
        this.ycqts = ycqts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.sjcqts
     *
     * @return the value of pro_main.sjcqts
     *
     * @mbg.generated
     */
    public Integer getSjcqts() {
        return sjcqts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.sjcqts
     *
     * @param sjcqts the value for pro_main.sjcqts
     *
     * @mbg.generated
     */
    public void setSjcqts(Integer sjcqts) {
        this.sjcqts = sjcqts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.sj
     *
     * @return the value of pro_main.sj
     *
     * @mbg.generated
     */
    public Integer getSj() {
        return sj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.sj
     *
     * @param sj the value for pro_main.sj
     *
     * @mbg.generated
     */
    public void setSj(Integer sj) {
        this.sj = sj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.bj
     *
     * @return the value of pro_main.bj
     *
     * @mbg.generated
     */
    public Integer getBj() {
        return bj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.bj
     *
     * @param bj the value for pro_main.bj
     *
     * @mbg.generated
     */
    public void setBj(Integer bj) {
        this.bj = bj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.nj
     *
     * @return the value of pro_main.nj
     *
     * @mbg.generated
     */
    public Integer getNj() {
        return nj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.nj
     *
     * @param nj the value for pro_main.nj
     *
     * @mbg.generated
     */
    public void setNj(Integer nj) {
        this.nj = nj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.hj
     *
     * @return the value of pro_main.hj
     *
     * @mbg.generated
     */
    public Integer getHj() {
        return hj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.hj
     *
     * @param hj the value for pro_main.hj
     *
     * @mbg.generated
     */
    public void setHj(Integer hj) {
        this.hj = hj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.qq
     *
     * @return the value of pro_main.qq
     *
     * @mbg.generated
     */
    public Integer getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.qq
     *
     * @param qq the value for pro_main.qq
     *
     * @mbg.generated
     */
    public void setQq(Integer qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.kg
     *
     * @return the value of pro_main.kg
     *
     * @mbg.generated
     */
    public Integer getKg() {
        return kg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.kg
     *
     * @param kg the value for pro_main.kg
     *
     * @mbg.generated
     */
    public void setKg(Integer kg) {
        this.kg = kg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.wdk
     *
     * @return the value of pro_main.wdk
     *
     * @mbg.generated
     */
    public Integer getWdk() {
        return wdk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.wdk
     *
     * @param wdk the value for pro_main.wdk
     *
     * @mbg.generated
     */
    public void setWdk(Integer wdk) {
        this.wdk = wdk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.cd
     *
     * @return the value of pro_main.cd
     *
     * @mbg.generated
     */
    public Integer getCd() {
        return cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.cd
     *
     * @param cd the value for pro_main.cd
     *
     * @mbg.generated
     */
    public void setCd(Integer cd) {
        this.cd = cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.tag
     *
     * @return the value of pro_main.tag
     *
     * @mbg.generated
     */
    public Boolean getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.tag
     *
     * @param tag the value for pro_main.tag
     *
     * @mbg.generated
     */
    public void setTag(Boolean tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.is_show
     *
     * @return the value of pro_main.is_show
     *
     * @mbg.generated
     */
    public Boolean getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.is_show
     *
     * @param isShow the value for pro_main.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.is_father
     *
     * @return the value of pro_main.is_father
     *
     * @mbg.generated
     */
    public Boolean getIsFather() {
        return isFather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.is_father
     *
     * @param isFather the value for pro_main.is_father
     *
     * @mbg.generated
     */
    public void setIsFather(Boolean isFather) {
        this.isFather = isFather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.pid
     *
     * @return the value of pro_main.pid
     *
     * @mbg.generated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.pid
     *
     * @param pid the value for pro_main.pid
     *
     * @mbg.generated
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.num1
     *
     * @return the value of pro_main.num1
     *
     * @mbg.generated
     */
    public Integer getNum1() {
        return num1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.num1
     *
     * @param num1 the value for pro_main.num1
     *
     * @mbg.generated
     */
    public void setNum1(Integer num1) {
        this.num1 = num1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.num2
     *
     * @return the value of pro_main.num2
     *
     * @mbg.generated
     */
    public Integer getNum2() {
        return num2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.num2
     *
     * @param num2 the value for pro_main.num2
     *
     * @mbg.generated
     */
    public void setNum2(Integer num2) {
        this.num2 = num2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.num3
     *
     * @return the value of pro_main.num3
     *
     * @mbg.generated
     */
    public Integer getNum3() {
        return num3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.num3
     *
     * @param num3 the value for pro_main.num3
     *
     * @mbg.generated
     */
    public void setNum3(Integer num3) {
        this.num3 = num3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.num4
     *
     * @return the value of pro_main.num4
     *
     * @mbg.generated
     */
    public Integer getNum4() {
        return num4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.num4
     *
     * @param num4 the value for pro_main.num4
     *
     * @mbg.generated
     */
    public void setNum4(Integer num4) {
        this.num4 = num4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.num5
     *
     * @return the value of pro_main.num5
     *
     * @mbg.generated
     */
    public Integer getNum5() {
        return num5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.num5
     *
     * @param num5 the value for pro_main.num5
     *
     * @mbg.generated
     */
    public void setNum5(Integer num5) {
        this.num5 = num5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.num6
     *
     * @return the value of pro_main.num6
     *
     * @mbg.generated
     */
    public Integer getNum6() {
        return num6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.num6
     *
     * @param num6 the value for pro_main.num6
     *
     * @mbg.generated
     */
    public void setNum6(Integer num6) {
        this.num6 = num6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.num7
     *
     * @return the value of pro_main.num7
     *
     * @mbg.generated
     */
    public Integer getNum7() {
        return num7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.num7
     *
     * @param num7 the value for pro_main.num7
     *
     * @mbg.generated
     */
    public void setNum7(Integer num7) {
        this.num7 = num7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.num8
     *
     * @return the value of pro_main.num8
     *
     * @mbg.generated
     */
    public Integer getNum8() {
        return num8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.num8
     *
     * @param num8 the value for pro_main.num8
     *
     * @mbg.generated
     */
    public void setNum8(Integer num8) {
        this.num8 = num8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.num9
     *
     * @return the value of pro_main.num9
     *
     * @mbg.generated
     */
    public Integer getNum9() {
        return num9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.num9
     *
     * @param num9 the value for pro_main.num9
     *
     * @mbg.generated
     */
    public void setNum9(Integer num9) {
        this.num9 = num9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.num10
     *
     * @return the value of pro_main.num10
     *
     * @mbg.generated
     */
    public Integer getNum10() {
        return num10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.num10
     *
     * @param num10 the value for pro_main.num10
     *
     * @mbg.generated
     */
    public void setNum10(Integer num10) {
        this.num10 = num10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.str_1
     *
     * @return the value of pro_main.str_1
     *
     * @mbg.generated
     */
    public String getStr1() {
        return str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.str_1
     *
     * @param str1 the value for pro_main.str_1
     *
     * @mbg.generated
     */
    public void setStr1(String str1) {
        this.str1 = str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.str_2
     *
     * @return the value of pro_main.str_2
     *
     * @mbg.generated
     */
    public String getStr2() {
        return str2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.str_2
     *
     * @param str2 the value for pro_main.str_2
     *
     * @mbg.generated
     */
    public void setStr2(String str2) {
        this.str2 = str2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.str_3
     *
     * @return the value of pro_main.str_3
     *
     * @mbg.generated
     */
    public String getStr3() {
        return str3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.str_3
     *
     * @param str3 the value for pro_main.str_3
     *
     * @mbg.generated
     */
    public void setStr3(String str3) {
        this.str3 = str3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.str_4
     *
     * @return the value of pro_main.str_4
     *
     * @mbg.generated
     */
    public String getStr4() {
        return str4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.str_4
     *
     * @param str4 the value for pro_main.str_4
     *
     * @mbg.generated
     */
    public void setStr4(String str4) {
        this.str4 = str4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.str_5
     *
     * @return the value of pro_main.str_5
     *
     * @mbg.generated
     */
    public String getStr5() {
        return str5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.str_5
     *
     * @param str5 the value for pro_main.str_5
     *
     * @mbg.generated
     */
    public void setStr5(String str5) {
        this.str5 = str5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.str_6
     *
     * @return the value of pro_main.str_6
     *
     * @mbg.generated
     */
    public String getStr6() {
        return str6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.str_6
     *
     * @param str6 the value for pro_main.str_6
     *
     * @mbg.generated
     */
    public void setStr6(String str6) {
        this.str6 = str6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.str_7
     *
     * @return the value of pro_main.str_7
     *
     * @mbg.generated
     */
    public String getStr7() {
        return str7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.str_7
     *
     * @param str7 the value for pro_main.str_7
     *
     * @mbg.generated
     */
    public void setStr7(String str7) {
        this.str7 = str7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.str_8
     *
     * @return the value of pro_main.str_8
     *
     * @mbg.generated
     */
    public String getStr8() {
        return str8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.str_8
     *
     * @param str8 the value for pro_main.str_8
     *
     * @mbg.generated
     */
    public void setStr8(String str8) {
        this.str8 = str8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.str_9
     *
     * @return the value of pro_main.str_9
     *
     * @mbg.generated
     */
    public String getStr9() {
        return str9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.str_9
     *
     * @param str9 the value for pro_main.str_9
     *
     * @mbg.generated
     */
    public void setStr9(String str9) {
        this.str9 = str9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.str_10
     *
     * @return the value of pro_main.str_10
     *
     * @mbg.generated
     */
    public String getStr10() {
        return str10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.str_10
     *
     * @param str10 the value for pro_main.str_10
     *
     * @mbg.generated
     */
    public void setStr10(String str10) {
        this.str10 = str10;
    }
}