package springboot.com.mvc.entity;

import springboot.template.mvc.entity.base.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pro_data
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ProData extends BaseEntity{
    private static final long serialVersionUID = -6026246617721023091L;

    public ProData() {
        super();
    }

    public ProData(String id) {
        super(id);
    }

    /** 早上数据*/
    private String mData;

    /** 下午数据*/
    private String pData;

    /** 标志 0正常 1 迟到 2 未打卡*/
    private Integer mTag;

    /** 标志 0正常 1 早退 2 未打卡*/
    private Integer pTag;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_data.m_data
     *
     * @return the value of pro_data.m_data
     *
     * @mbg.generated
     */
    public String getmData() {
        return mData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_data.m_data
     *
     * @param mData the value for pro_data.m_data
     *
     * @mbg.generated
     */
    public void setmData(String mData) {
        this.mData = mData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_data.p_data
     *
     * @return the value of pro_data.p_data
     *
     * @mbg.generated
     */
    public String getpData() {
        return pData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_data.p_data
     *
     * @param pData the value for pro_data.p_data
     *
     * @mbg.generated
     */
    public void setpData(String pData) {
        this.pData = pData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_data.m_tag
     *
     * @return the value of pro_data.m_tag
     *
     * @mbg.generated
     */
    public Integer getmTag() {
        return mTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_data.m_tag
     *
     * @param mTag the value for pro_data.m_tag
     *
     * @mbg.generated
     */
    public void setmTag(Integer mTag) {
        this.mTag = mTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_data.p_tag
     *
     * @return the value of pro_data.p_tag
     *
     * @mbg.generated
     */
    public Integer getpTag() {
        return pTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_data.p_tag
     *
     * @param pTag the value for pro_data.p_tag
     *
     * @mbg.generated
     */
    public void setpTag(Integer pTag) {
        this.pTag = pTag;
    }
}