package springboot.com.mvc.entity;

import springboot.template.mvc.entity.base.DateEntity;


/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pro_main
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ProMain extends DateEntity{
    private static final long serialVersionUID = -105447164568305484L;

    public ProMain() {
        super();
    }
    public ProMain(String id){
        super(id);
    }

    /** */
    private String userId;

    /** 序号*/
    private Integer sort;

    /** */
    private ProData d1;

    /** */
    private ProData d2;

    /** */
    private ProData d3;

    /** */
    private ProData d4;

    /** */
    private ProData d5;

    /** */
    private ProData d6;

    /** */
    private ProData d7;


    /** */
    private ProData d8;

    /** */
    private ProData d9;

    /** */
    private ProData d10;

    /** */
    private ProData d11;

    /** */
    private ProData d12;

    /** */
    private ProData d13;

    /** */
    private ProData d14;

    /** */
    private ProData d15;

    /** */
    private ProData d16;

    /** */
    private ProData d17;

    /** */
    private ProData d18;

    /** */
    private ProData d19;

    /** */
    private ProData d20;

    /** */
    private ProData d21;

    /** */
    private ProData d22;

    /** */
    private ProData d23;

    /** */
    private ProData d24;

    /** */
    private ProData d25;

    /** */
    private ProData d26;

    /** */
    private ProData d27;

    /** */
    private ProData d28;

    /** */
    private ProData d29;

    /** */
    private ProData d30;

    /** */
    private ProData d31;

    /** 系统 年*/
    private Integer year;

    /** 系统 月*/
    private Integer month;

    /** 系统 日*/
    private Integer day;

    /** 备注*/
    private String remarks;

    /** 应出勤天数*/
    private Integer ycqts;

    /** 实际出勤天数*/
    private Integer sjcqts;

    /** 事假*/
    private Integer sj;

    /** 病假*/
    private Integer bj;

    /** 年假*/
    private Integer nj;

    /** 婚假*/
    private Integer hj;

    /** 缺勤*/
    private Integer qq;

    /** 旷工*/
    private Integer kg;

    /** 忘打卡*/
    private Integer wdk;

    /** 迟到*/
    private Integer cd;

    /** 原始记录id*/
    private String fatherId;

    /** */
    private Integer num1;

    /** */
    private Integer num2;

    /** */
    private Integer num3;

    /** */
    private Integer num4;

    /** */
    private Integer num5;

    /** */
    private Integer num9;

    /** */
    private String str1;

    /** */
    private String str2;

    /** */
    private String str3;

    /** */
    private String str4;

    /** */
    private String str5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.user_id
     *
     * @return the value of pro_main.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.user_id
     *
     * @param userId the value for pro_main.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.sort
     *
     * @return the value of pro_main.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.sort
     *
     * @param sort the value for pro_main.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public ProData getD1() {
        return d1;
    }

    public void setD1(ProData d1) {
        this.d1 = d1;
    }

    public ProData getD2() {
        return d2;
    }

    public void setD2(ProData d2) {
        this.d2 = d2;
    }

    public ProData getD3() {
        return d3;
    }

    public void setD3(ProData d3) {
        this.d3 = d3;
    }

    public ProData getD4() {
        return d4;
    }

    public void setD4(ProData d4) {
        this.d4 = d4;
    }

    public ProData getD5() {
        return d5;
    }

    public void setD5(ProData d5) {
        this.d5 = d5;
    }

    public ProData getD6() {
        return d6;
    }

    public void setD6(ProData d6) {
        this.d6 = d6;
    }

    public ProData getD7() {
        return d7;
    }

    public void setD7(ProData d7) {
        this.d7 = d7;
    }

    public ProData getD8() {
        return d8;
    }

    public void setD8(ProData d8) {
        this.d8 = d8;
    }

    public ProData getD9() {
        return d9;
    }

    public void setD9(ProData d9) {
        this.d9 = d9;
    }

    public ProData getD10() {
        return d10;
    }

    public void setD10(ProData d10) {
        this.d10 = d10;
    }

    public ProData getD11() {
        return d11;
    }

    public void setD11(ProData d11) {
        this.d11 = d11;
    }

    public ProData getD12() {
        return d12;
    }

    public void setD12(ProData d12) {
        this.d12 = d12;
    }

    public ProData getD13() {
        return d13;
    }

    public void setD13(ProData d13) {
        this.d13 = d13;
    }

    public ProData getD14() {
        return d14;
    }

    public void setD14(ProData d14) {
        this.d14 = d14;
    }

    public ProData getD15() {
        return d15;
    }

    public void setD15(ProData d15) {
        this.d15 = d15;
    }

    public ProData getD16() {
        return d16;
    }

    public void setD16(ProData d16) {
        this.d16 = d16;
    }

    public ProData getD17() {
        return d17;
    }

    public void setD17(ProData d17) {
        this.d17 = d17;
    }

    public ProData getD18() {
        return d18;
    }

    public void setD18(ProData d18) {
        this.d18 = d18;
    }

    public ProData getD19() {
        return d19;
    }

    public void setD19(ProData d19) {
        this.d19 = d19;
    }

    public ProData getD20() {
        return d20;
    }

    public void setD20(ProData d20) {
        this.d20 = d20;
    }

    public ProData getD21() {
        return d21;
    }

    public void setD21(ProData d21) {
        this.d21 = d21;
    }

    public ProData getD22() {
        return d22;
    }

    public void setD22(ProData d22) {
        this.d22 = d22;
    }

    public ProData getD23() {
        return d23;
    }

    public void setD23(ProData d23) {
        this.d23 = d23;
    }

    public ProData getD24() {
        return d24;
    }

    public void setD24(ProData d24) {
        this.d24 = d24;
    }

    public ProData getD25() {
        return d25;
    }

    public void setD25(ProData d25) {
        this.d25 = d25;
    }

    public ProData getD26() {
        return d26;
    }

    public void setD26(ProData d26) {
        this.d26 = d26;
    }

    public ProData getD27() {
        return d27;
    }

    public void setD27(ProData d27) {
        this.d27 = d27;
    }

    public ProData getD28() {
        return d28;
    }

    public void setD28(ProData d28) {
        this.d28 = d28;
    }

    public ProData getD29() {
        return d29;
    }

    public void setD29(ProData d29) {
        this.d29 = d29;
    }

    public ProData getD30() {
        return d30;
    }

    public void setD30(ProData d30) {
        this.d30 = d30;
    }

    public ProData getD31() {
        return d31;
    }

    public void setD31(ProData d31) {
        this.d31 = d31;
    }

    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.year
     *
     * @param year the value for pro_main.year
     *
     * @mbg.generated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.month
     *
     * @return the value of pro_main.month
     *
     * @mbg.generated
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.month
     *
     * @param month the value for pro_main.month
     *
     * @mbg.generated
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.day
     *
     * @return the value of pro_main.day
     *
     * @mbg.generated
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.day
     *
     * @param day the value for pro_main.day
     *
     * @mbg.generated
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.remarks
     *
     * @return the value of pro_main.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.remarks
     *
     * @param remarks the value for pro_main.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.ycqts
     *
     * @return the value of pro_main.ycqts
     *
     * @mbg.generated
     */
    public Integer getYcqts() {
        return ycqts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.ycqts
     *
     * @param ycqts the value for pro_main.ycqts
     *
     * @mbg.generated
     */
    public void setYcqts(Integer ycqts) {
        this.ycqts = ycqts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.sjcqts
     *
     * @return the value of pro_main.sjcqts
     *
     * @mbg.generated
     */
    public Integer getSjcqts() {
        return sjcqts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.sjcqts
     *
     * @param sjcqts the value for pro_main.sjcqts
     *
     * @mbg.generated
     */
    public void setSjcqts(Integer sjcqts) {
        this.sjcqts = sjcqts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.sj
     *
     * @return the value of pro_main.sj
     *
     * @mbg.generated
     */
    public Integer getSj() {
        return sj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.sj
     *
     * @param sj the value for pro_main.sj
     *
     * @mbg.generated
     */
    public void setSj(Integer sj) {
        this.sj = sj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.bj
     *
     * @return the value of pro_main.bj
     *
     * @mbg.generated
     */
    public Integer getBj() {
        return bj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.bj
     *
     * @param bj the value for pro_main.bj
     *
     * @mbg.generated
     */
    public void setBj(Integer bj) {
        this.bj = bj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.nj
     *
     * @return the value of pro_main.nj
     *
     * @mbg.generated
     */
    public Integer getNj() {
        return nj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.nj
     *
     * @param nj the value for pro_main.nj
     *
     * @mbg.generated
     */
    public void setNj(Integer nj) {
        this.nj = nj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.hj
     *
     * @return the value of pro_main.hj
     *
     * @mbg.generated
     */
    public Integer getHj() {
        return hj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.hj
     *
     * @param hj the value for pro_main.hj
     *
     * @mbg.generated
     */
    public void setHj(Integer hj) {
        this.hj = hj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.qq
     *
     * @return the value of pro_main.qq
     *
     * @mbg.generated
     */
    public Integer getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.qq
     *
     * @param qq the value for pro_main.qq
     *
     * @mbg.generated
     */
    public void setQq(Integer qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.kg
     *
     * @return the value of pro_main.kg
     *
     * @mbg.generated
     */
    public Integer getKg() {
        return kg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.kg
     *
     * @param kg the value for pro_main.kg
     *
     * @mbg.generated
     */
    public void setKg(Integer kg) {
        this.kg = kg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.wdk
     *
     * @return the value of pro_main.wdk
     *
     * @mbg.generated
     */
    public Integer getWdk() {
        return wdk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.wdk
     *
     * @param wdk the value for pro_main.wdk
     *
     * @mbg.generated
     */
    public void setWdk(Integer wdk) {
        this.wdk = wdk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.cd
     *
     * @return the value of pro_main.cd
     *
     * @mbg.generated
     */
    public Integer getCd() {
        return cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.cd
     *
     * @param cd the value for pro_main.cd
     *
     * @mbg.generated
     */
    public void setCd(Integer cd) {
        this.cd = cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.father_id
     *
     * @return the value of pro_main.father_id
     *
     * @mbg.generated
     */
    public String getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.father_id
     *
     * @param fatherId the value for pro_main.father_id
     *
     * @mbg.generated
     */
    public void setFatherId(String fatherId) {
        this.fatherId = fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.num1
     *
     * @return the value of pro_main.num1
     *
     * @mbg.generated
     */
    public Integer getNum1() {
        return num1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.num1
     *
     * @param num1 the value for pro_main.num1
     *
     * @mbg.generated
     */
    public void setNum1(Integer num1) {
        this.num1 = num1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.num2
     *
     * @return the value of pro_main.num2
     *
     * @mbg.generated
     */
    public Integer getNum2() {
        return num2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.num2
     *
     * @param num2 the value for pro_main.num2
     *
     * @mbg.generated
     */
    public void setNum2(Integer num2) {
        this.num2 = num2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.num3
     *
     * @return the value of pro_main.num3
     *
     * @mbg.generated
     */
    public Integer getNum3() {
        return num3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.num3
     *
     * @param num3 the value for pro_main.num3
     *
     * @mbg.generated
     */
    public void setNum3(Integer num3) {
        this.num3 = num3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.num4
     *
     * @return the value of pro_main.num4
     *
     * @mbg.generated
     */
    public Integer getNum4() {
        return num4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.num4
     *
     * @param num4 the value for pro_main.num4
     *
     * @mbg.generated
     */
    public void setNum4(Integer num4) {
        this.num4 = num4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.num5
     *
     * @return the value of pro_main.num5
     *
     * @mbg.generated
     */
    public Integer getNum5() {
        return num5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.num5
     *
     * @param num5 the value for pro_main.num5
     *
     * @mbg.generated
     */
    public void setNum5(Integer num5) {
        this.num5 = num5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.num9
     *
     * @return the value of pro_main.num9
     *
     * @mbg.generated
     */
    public Integer getNum9() {
        return num9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.num9
     *
     * @param num9 the value for pro_main.num9
     *
     * @mbg.generated
     */
    public void setNum9(Integer num9) {
        this.num9 = num9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.str_1
     *
     * @return the value of pro_main.str_1
     *
     * @mbg.generated
     */
    public String getStr1() {
        return str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.str_1
     *
     * @param str1 the value for pro_main.str_1
     *
     * @mbg.generated
     */
    public void setStr1(String str1) {
        this.str1 = str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.str_2
     *
     * @return the value of pro_main.str_2
     *
     * @mbg.generated
     */
    public String getStr2() {
        return str2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.str_2
     *
     * @param str2 the value for pro_main.str_2
     *
     * @mbg.generated
     */
    public void setStr2(String str2) {
        this.str2 = str2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.str_3
     *
     * @return the value of pro_main.str_3
     *
     * @mbg.generated
     */
    public String getStr3() {
        return str3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.str_3
     *
     * @param str3 the value for pro_main.str_3
     *
     * @mbg.generated
     */
    public void setStr3(String str3) {
        this.str3 = str3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.str_4
     *
     * @return the value of pro_main.str_4
     *
     * @mbg.generated
     */
    public String getStr4() {
        return str4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.str_4
     *
     * @param str4 the value for pro_main.str_4
     *
     * @mbg.generated
     */
    public void setStr4(String str4) {
        this.str4 = str4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_main.str_5
     *
     * @return the value of pro_main.str_5
     *
     * @mbg.generated
     */
    public String getStr5() {
        return str5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_main.str_5
     *
     * @param str5 the value for pro_main.str_5
     *
     * @mbg.generated
     */
    public void setStr5(String str5) {
        this.str5 = str5;
    }
}