server:
  port: 8080
spring:
  application:
    name: Cloud-Server-8080
eureka:
  instance:
    hostname: localhost
  client:
    #自己是eureka server
    register-with-eureka: false
    #注册中心不去自己
    fetch-registry: false
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

