package springboot.template.mvc.mapper;

import springboot.template.mvc.entity.SysDirectory;

import java.util.List;

public interface SysDirectoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_directory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_directory
     *
     * @mbg.generated
     */
    int insert(SysDirectory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_directory
     *
     * @mbg.generated
     */
    int insertSelective(SysDirectory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_directory
     *
     * @mbg.generated
     */
    SysDirectory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_directory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysDirectory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_directory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysDirectory record);

    List<SysDirectory> getUserDirectorys(String userId);
}