server:
  port: 8080
spring:
  application:
    name: eurekaribbon
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:80/eureka/

