package springboot.template.mvc.entity.base;


import java.util.Date;

/**
 * @Auther HUGH
 * @Date 2018/7/15
 * @Description DateEntity
 */
public class DateEntity extends BaseEntity {
    private static final long serialVersionUID = 7890837950729944006L;

    /** */
    protected Date createTime;
    /** */
    protected String createUserId;
    /** */
    protected Date updateTime;
    /** */
    protected String updateUserId;

    public DateEntity(){
        super();
    }
    public DateEntity(String id) {
        super(id);
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.create_time
     *
     * @return the value of sys_department.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.create_time
     *
     * @param createTime the value for sys_department.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.create_user_id
     *
     * @return the value of sys_department.create_user_id
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.create_user_id
     *
     * @param createUserId the value for sys_department.create_user_id
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.update_time
     *
     * @return the value of sys_department.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.update_time
     *
     * @param updateTime the value for sys_department.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.update_user_id
     *
     * @return the value of sys_department.update_user_id
     * @mbg.generated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.update_user_id
     *
     * @param updateUserId the value for sys_department.update_user_id
     * @mbg.generated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }
}
