package springboot.template.mvc.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table role_directory
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class RoleDirectory {
    /** */
    private String id;

    /** 角色id*/
    private String roleId;
    private  SysRole sysRole;

    /** 目录表id*/
    private String directoryId;
    private SysDirectory sysDirectory;
    public RoleDirectory(){
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_directory.id
     *
     * @return the value of role_directory.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_directory.id
     *
     * @param id the value for role_directory.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_directory.role_id
     *
     * @return the value of role_directory.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_directory.role_id
     *
     * @param roleId the value for role_directory.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_directory.directory_id
     *
     * @return the value of role_directory.directory_id
     *
     * @mbg.generated
     */
    public String getDirectoryId() {
        return directoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_directory.directory_id
     *
     * @param directoryId the value for role_directory.directory_id
     *
     * @mbg.generated
     */
    public void setDirectoryId(String directoryId) {
        this.directoryId = directoryId;
    }

    public SysRole getSysRole() {
        return sysRole;
    }

    public void setSysRole(SysRole sysRole) {
        this.sysRole = sysRole;
    }

    public SysDirectory getSysDirectory() {
        return sysDirectory;
    }

    public void setSysDirectory(SysDirectory sysDirectory) {
        this.sysDirectory = sysDirectory;
    }
}