package springboot.template.mvc.entity;

import springboot.template.mvc.entity.base.BaseEntity;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_directory
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysDirectory extends BaseEntity {
    private static final long serialVersionUID = -14119579202188850L;
    /**
     * 程序对应url地址
     */
    private String url;
    /**
     * 名称
     */
    private String urlName;
    /**
     * 图标
     */
    private String urlImg;
    /**
     * 类型 0 url 1 按钮
     */
    private Integer type;
    /**
     * 父id
     */
    private String fatherId;
    /** */
    private String fatherIds;
    /**
     * 排序
     */
    private Integer sort;
    /**
     * 权限 标识
     */
    private String permission;
    /** */
    private String remarks;
    /** */
    private Date createTime;
    /** */
    private String createUserId;
    /** */
    private Date updateTime;
    /** */
    private String updateUserId;
    /**
     * 是否禁用 0 否 1是
     */
    private Integer isDisable;

    /**
     * This method returns the value of the database column sys_directory.url
     *
     * @return the value of sys_directory.url
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * @param url the value for sys_directory.url
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * @return the value of sys_directory.url_name
     * @mbg.generated
     */
    public String getUrlName() {
        return urlName;
    }

    /**
     * @param urlName the value for sys_directory.url_name
     * @mbg.generated
     */
    public void setUrlName(String urlName) {
        this.urlName = urlName;
    }

    /**
     * @return the value of sys_directory.url_img
     * @mbg.generated
     */
    public String getUrlImg() {
        return urlImg;
    }

    /**
     * _img
     *
     * @param urlImg the value for sys_directory.url_img
     * @mbg.generated
     */
    public void setUrlImg(String urlImg) {
        this.urlImg = urlImg;
    }

    /**
     * @return the value of sys_directory.type
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * @param type the value for sys_directory.type
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * @return the value of sys_directory.father_id
     * @mbg.generated
     */
    public String getFatherId() {
        return fatherId;
    }

    /**
     * @param fatherId the value for sys_directory.father_id
     * @mbg.generated
     */
    public void setFatherId(String fatherId) {
        this.fatherId = fatherId;
    }

    /**
     * @return the value of sys_directory.father_ids
     * @mbg.generated
     */
    public String getFatherIds() {
        return fatherIds;
    }

    /**
     * @param fatherIds the value for sys_directory.father_ids
     * @mbg.generated
     */
    public void setFatherIds(String fatherIds) {
        this.fatherIds = fatherIds;
    }

    /**
     * @return the value of sys_directory.sort
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * @param sort the value for sys_directory.sort
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * @return the value of sys_directory.permission
     * @mbg.generated
     */
    public String getPermission() {
        return permission;
    }

    /**
     * @param permission the value for sys_directory.permission
     * @mbg.generated
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * @return the value of sys_directory.remarks
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * @param remarks the value for sys_directory.remarks
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * @return the value of sys_directory.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime the value for sys_directory.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return the value of sys_directory.create_user_id
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * @param createUserId the value for sys_directory.create_user_id
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * @return the value of sys_directory.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * @param updateTime the value for sys_directory.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * @return the value of sys_directory.update_user_id
     * @mbg.generated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * @param updateUserId the value for sys_directory.update_user_id
     * @mbg.generated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * @return the value of sys_directory.is_disable
     * @mbg.generated
     */
    public Integer getIsDisable() {
        return isDisable;
    }

    /**
     * @param isDisable the value for sys_directory.is_disable
     * @mbg.generated
     */
    public void setIsDisable(Integer isDisable) {
        this.isDisable = isDisable;
    }
}