package springboot.template.mvc.entity;

import springboot.template.mvc.entity.base.DateEntity;


/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_department
 *
 * @mbg.generated do_not_delete_uring_merge
 */
public class SysDepartment extends DateEntity {
    private static final long serialVersionUID = 5286463876425329863L;

    public SysDepartment() {
       super();
    }

    public SysDepartment(String id) {
        super(id);
    }

    /**
     * 部门名称
     */
    private String departmentName;
    /**
     * 父部门id
     */
    private String fatherId;
    /**
     * 排序
     */
    private Integer sort;
    /**
     * 备注
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.department_name
     *
     * @return the value of sys_department.department_name
     * @mbg.generated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.department_name
     *
     * @param departmentName the value for sys_department.department_name
     * @mbg.generated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.father_id
     *
     * @return the value of sys_department.father_id
     * @mbg.generated
     */
    public String getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.father_id
     *
     * @param fatherId the value for sys_department.father_id
     * @mbg.generated
     */
    public void setFatherId(String fatherId) {
        this.fatherId = fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.sort
     *
     * @return the value of sys_department.sort
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.sort
     *
     * @param sort the value for sys_department.sort
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_department.remarks
     *
     * @return the value of sys_department.remarks
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_department.remarks
     *
     * @param remarks the value for sys_department.remarks
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Override
    public String toString() {
        return "SysDepartment{" +
                "departmentName='" + departmentName + '\'' +
                ", fatherId='" + fatherId + '\'' +
                ", sort=" + sort +
                ", remarks='" + remarks + '\'' +
                ", createTime=" + createTime +
                ", createUserId='" + createUserId + '\'' +
                ", updateTime=" + updateTime +
                ", updateUserId='" + updateUserId + '\'' +
                ", isDisable=" + isDisable +
                ", isNewCreate=" + isNewCreate +
                ", id='" + id + '\'' +
                '}';
    }
}