package springboot.template.mvc.entity;

import springboot.template.mvc.entity.base.BaseEntity;
import springboot.template.mvc.entity.base.DateEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_permission
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysPermission extends DateEntity {
    private static final long serialVersionUID = -308404943148366278L;
    public SysPermission(){
       super();
    }
    public SysPermission(String id){
        super(id);
    }
    /** 程序对应url地址*/
    private String url;

    /** 名称*/
    private String urlName;

    /** 图标*/
    private String urlImg;

    /** 类型 0 url 1 按钮*/
    private Integer type;

    /** 父id*/
    private String fatherId;

    /** 所有父id ','分割*/
    private String fatherIds;

    /** 排序*/
    private Integer sort;

    /** 权限 标识*/
    private String permission;

    /** */
    private String remarks;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.url
     *
     * @return the value of sys_permission.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.url
     *
     * @param url the value for sys_permission.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.url_name
     *
     * @return the value of sys_permission.url_name
     *
     * @mbg.generated
     */
    public String getUrlName() {
        return urlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.url_name
     *
     * @param urlName the value for sys_permission.url_name
     *
     * @mbg.generated
     */
    public void setUrlName(String urlName) {
        this.urlName = urlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.url_img
     *
     * @return the value of sys_permission.url_img
     *
     * @mbg.generated
     */
    public String getUrlImg() {
        return urlImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.url_img
     *
     * @param urlImg the value for sys_permission.url_img
     *
     * @mbg.generated
     */
    public void setUrlImg(String urlImg) {
        this.urlImg = urlImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.type
     *
     * @return the value of sys_permission.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.type
     *
     * @param type the value for sys_permission.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.father_id
     *
     * @return the value of sys_permission.father_id
     *
     * @mbg.generated
     */
    public String getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.father_id
     *
     * @param fatherId the value for sys_permission.father_id
     *
     * @mbg.generated
     */
    public void setFatherId(String fatherId) {
        this.fatherId = fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.father_ids
     *
     * @return the value of sys_permission.father_ids
     *
     * @mbg.generated
     */
    public String getFatherIds() {
        return fatherIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.father_ids
     *
     * @param fatherIds the value for sys_permission.father_ids
     *
     * @mbg.generated
     */
    public void setFatherIds(String fatherIds) {
        this.fatherIds = fatherIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.sort
     *
     * @return the value of sys_permission.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.sort
     *
     * @param sort the value for sys_permission.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.permission
     *
     * @return the value of sys_permission.permission
     *
     * @mbg.generated
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.permission
     *
     * @param permission the value for sys_permission.permission
     *
     * @mbg.generated
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.remarks
     *
     * @return the value of sys_permission.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.remarks
     *
     * @param remarks the value for sys_permission.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

}