server:
  port: 1111
eureka:
  instance:
    hostname: localhost
  client:
    //不向注册中心注册自己
    register-with-eureka: false
    注册中心不去检索服务
    fetch-registry: false
    eureka-server-urlcontext: http://${eureka.instance.hostname}:${server.port}/eureka/
