server:
  port: 8085
spring:
  application:
    name: Cloud-Zuul-8085
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8080/eureka/
zuul:
  routes:
    a:
      path: /a/**
      serviceId: Cloud-Hystrix-Ribbon-8083
    b:
      path: /b/**
      serviceId: Cloud-Hystrix-Feign-8084
