server:
  port: 8091
spring:
  application:
    name: eurekaclient
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:80/eureka/

